export type WordDetail = {
  ipa: string;
  part: string;
  collocations: string[];
  bookSentence: string;
  bookSentenceZh: string;
  source: string;
};

const d = (ipa: string, part: string, collocations: string[], bookSentence: string, bookSentenceZh: string, source: string): WordDetail => ({ ipa, part, collocations, bookSentence, bookSentenceZh, source });

export const wordDetails: Record<string, WordDetail> = {
  "meet the neighbours": d("/miːt ðə ˈneɪbəz/", "动词短语", ["meet my neighbours", "new neighbours"], "Then, I met my neighbours.", "然后，我认识了邻居。", "教材 P.2 B（按教材词库补全）"),
  "make new friends": d("/meɪk njuː frendz/", "动词短语", ["make new friends", "like my new friends"], "I’m in a new school, and I like my new friends.", "我在一所新学校，并且我喜欢我的新朋友。", "教材 P.10 Jobs"),
  "go ice skating": d("/ɡəʊ aɪs ˈskeɪtɪŋ/", "动词短语", ["go ice skating", "went ice skating"], "In the afternoon, we went ice skating.", "下午，我们去滑冰了。", "教材 P.2 B（按教材词库补全）"),
  "throw snowballs": d("/θrəʊ ˈsnəʊbɔːlz/", "动词短语", ["throw snowballs", "throw snowballs at each other"], "We threw snowballs at each other.", "我们互相扔雪球。", "教材 P.2 B（按教材词库补全）"),
  "ago": d("/əˈɡəʊ/", "副词", ["one month ago", "years ago"], "We moved to Shanghai one month ago.", "我们一个月前搬到了上海。", "教材 P.3 C"),
  "postcard": d("/ˈpəʊstkɑːd/", "名词", ["a postcard", "postcards to a friend"], "We moved to Shanghai one month ago.", "我们一个月前搬到了上海。", "教材 P.3 Postcards to a friend"),
  "lonely": d("/ˈləʊnli/", "形容词", ["feel lonely", "felt lonely"], "I feel lonely.", "我感到孤单。", "教材 P.4 28th January"),
  "miss": d("/mɪs/", "动词", ["miss you", "miss you so much"], "I miss you so much!", "我非常想念你！", "教材 P.4 28th January"),
  "PS": d("/ˌpiː ˈes/", "名词；书信用语", ["PS:", "add a PS"], "PS: Ningning and Yuanyuan from the band invited me to Happy Valley this weekend.", "附言：乐队里的宁宁和媛媛邀请我这周末去欢乐谷。", "教材 P.4 22nd February"),
  "homeless": d("/ˈhəʊmləs/", "形容词", ["homeless animals", "help homeless animals"], "On Saturday, Ningning, Yuanyuan and I are going to play in a concert and raise money for homeless animals.", "星期六，我和宁宁、媛媛要参加音乐会，为无家可归的动物筹款。", "教材 P.5 20th March"),
  "ski": d("/skiː/", "动词", ["ski in winter", "ski or skate"], "I want to move to Harbin. When I move there, I can enjoy winter sports.", "我想搬到哈尔滨。搬去那里后，我可以享受冬季运动。", "教材 P.9 B"),
  "raise money": d("/reɪz ˈmʌni/", "动词短语", ["raise money", "raise money for homeless animals"], "On Saturday, Ningning, Yuanyuan and I are going to play in a concert and raise money for homeless animals.", "星期六，我和宁宁、媛媛要参加音乐会，为无家可归的动物筹款。", "教材 P.5 20th March"),
  "I’m so excited!": d("/aɪm səʊ ɪkˈsaɪtɪd/", "日常表达", ["be excited", "be excited about"], "I’m so excited!", "我太兴奋了！", "教材 P.4 22nd February"),

  "ink painting": d("/ɪŋk ˈpeɪntɪŋ/", "名词短语", ["be good at ink painting", "do ink painting"], "He was good at ink painting.", "他擅长水墨画。", "教材 P.17 Xu Beihong"),
  "oil painting": d("/ɔɪl ˈpeɪntɪŋ/", "名词短语", ["do oil painting", "an oil painting"], "He did oil painting.", "他画油画。", "教材 P.17 Vincent van Gogh"),
  "artist": d("/ˈɑːtɪst/", "名词", ["a Chinese artist", "be an artist"], "Xu Beihong was a Chinese artist.", "徐悲鸿是一位中国艺术家。", "教材 P.17 Xu Beihong"),
  "paintbrush": d("/ˈpeɪntbrʌʃ/", "名词", ["a paintbrush", "paint with a paintbrush"], "The artists often paint mountains, flowers and birds.", "艺术家们经常画山、花和鸟。", "教材 P.14 B；单词见 P.14 A"),
  "powerful": d("/ˈpaʊəfəl/", "形容词", ["very powerful", "powerful art"], "Art can be very powerful.", "艺术可以很有感染力。", "教材 P.16 The power of art"),
  "express": d("/ɪkˈspres/", "动词", ["express themselves", "express their feelings"], "Artists try to express themselves and touch people’s hearts.", "艺术家努力表达自己并打动人心。", "教材 P.16 The power of art"),
  "painter": d("/ˈpeɪntə/", "名词", ["painters’ feelings", "painters’ own styles"], "Painters have their own styles.", "画家有自己的风格。", "教材 P.16 Painting with style"),
  "own": d("/əʊn/", "形容词", ["their own styles", "my own"], "Painters have their own styles.", "画家有自己的风格。", "教材 P.16 Painting with style"),
  "anyone": d("/ˈeniwʌn/", "代词", ["anyone can", "anyone can be an artist"], "Anyone can be an artist.", "任何人都可以成为艺术家。", "教材 P.19 A"),
  "share": d("/ʃeə/", "动词", ["share the beauty of art", "share with others"], "People dance because they can express their feelings.", "人们跳舞是因为他们可以表达自己的感受。", "教材 P.21 B；搭配见同页词组"),
  "touch one’s heart": d("/tʌtʃ wʌnz hɑːt/", "动词短语", ["touch people’s hearts", "touch one’s heart"], "Artists try to express themselves and touch people’s hearts.", "艺术家努力表达自己并打动人心。", "教材 P.16 The power of art"),
  "show one’s feelings": d("/ʃəʊ wʌnz ˈfiːlɪŋz/", "动词短语", ["show the painter’s feelings", "show one’s feelings"], "But all paintings show the painters’ feelings.", "但所有画作都表现了画家的感受。", "教材 P.16 Painting with style"),
  "be famous for": d("/bi ˈfeɪməs fɔː/", "动词短语", ["be famous for using bright colours", "be famous for art"], "He is famous for using bright colours.", "他以使用鲜艳色彩而闻名。", "教材 P.17 Vincent van Gogh"),

  "protect": d("/prəˈtekt/", "动词", ["protect ourselves", "protect our Earth"], "How should we protect ourselves?", "我们应该怎样保护自己？", "教材 P.25 Unit 3 大问题"),
  "warm up": d("/wɔːm ʌp/", "动词短语", ["warm up first", "warm up before doing exercise"], "Always warm up first.", "一定要先热身。", "教材 P.29 Sports safety tips"),
  "get hurt": d("/ɡet hɜːt/", "动词短语", ["get hurt", "got hurt"], "Wang Hao got hurt and broke his arm.", "王浩受伤并摔断了手臂。", "教材 P.28 Student breaks arm"),
  "call for help": d("/kɔːl fə help/", "动词短语", ["call for help", "call loudly for help"], "Next, he called for help.", "接着，他呼救。", "教材 P.32 听力填空（按教材答案补全）"),
  "break": d("/breɪk/", "动词", ["break one’s arm", "broke his arm"], "Yesterday afternoon, Wang Hao broke his arm at the skatepark.", "昨天下午，王浩在滑板公园摔断了手臂。", "教材 P.28 Student breaks arm"),
  "arm": d("/ɑːm/", "名词", ["break one’s arm", "his arm"], "Yesterday afternoon, Wang Hao broke his arm at the skatepark.", "昨天下午，王浩在滑板公园摔断了手臂。", "教材 P.28 Student breaks arm"),
  "skatepark": d("/ˈskeɪtpɑːk/", "名词", ["at the skatepark", "a safe skatepark"], "Yesterday afternoon, Wang Hao broke his arm at the skatepark.", "昨天下午，王浩在滑板公园摔断了手臂。", "教材 P.28 Student breaks arm"),
  "luckily": d("/ˈlʌkɪli/", "副词", ["Luckily, ...", "luckily for him"], "Luckily, he didn’t have more injuries, because he wore a helmet and pads.", "幸运的是，他因为戴了头盔和护垫，没有更多伤处。", "教材 P.28 Student breaks arm"),
  "helmet": d("/ˈhelmɪt/", "名词", ["wear a helmet", "choose a helmet"], "Luckily, he didn’t have more injuries, because he wore a helmet and pads.", "幸运的是，他因为戴了头盔和护垫，没有更多伤处。", "教材 P.28 Student breaks arm"),
  "pad": d("/pæd/", "名词", ["wear pads", "a helmet and pads"], "Luckily, he didn’t have more injuries, because he wore a helmet and pads.", "幸运的是，他因为戴了头盔和护垫，没有更多伤处。", "教材 P.28 Student breaks arm"),
  "call an ambulance": d("/kɔːl ən ˈæmbjələns/", "动词短语", ["call an ambulance", "the ambulance arrived"], "Xu Li, a friend of Wang Hao, called an ambulance.", "王浩的朋友徐丽叫了救护车。", "教材 P.28 Student breaks arm"),
  "check injuries": d("/tʃek ˈɪndʒəriz/", "动词短语", ["check injuries", "checked Wang Hao’s injuries"], "First, the emergency workers checked Wang Hao’s injuries.", "首先，急救人员检查了王浩的伤情。", "教材 P.29"),
  "emergency worker": d("/ɪˈmɜːdʒənsi ˈwɜːkə/", "名词短语", ["emergency workers", "the emergency workers checked"], "First, the emergency workers checked Wang Hao’s injuries.", "首先，急救人员检查了王浩的伤情。", "教材 P.29"),
  "X-ray": d("/ˈeks reɪ/", "名词", ["have an X-ray", "for an X-ray"], "Then, they took him to the hospital for an X-ray.", "然后，他们送他去医院拍 X 光片。", "教材 P.29"),
  "choose": d("/tʃuːz/", "动词", ["choose a safe place", "choose a helmet"], "Choose a safe place.", "选择一个安全的地方。", "教材 P.29 Sports safety tips"),
  "lost": d("/lɒst/", "形容词", ["be lost", "a lost girl"], "A little girl is lost in the city.", "一个小女孩在城市里迷路了。", "教材 P.33 B"),

  "push": d("/pʊʃ/", "动词；名词", ["push a door", "push things away"], "When we push, it moves people or things away from us.", "当我们推时，推力使人或物体远离我们。", "教材 P.40 Forces"),
  "pull": d("/pʊl/", "动词；名词", ["pull a door", "pull things towards us"], "When we pull, it moves people or things towards us.", "当我们拉时，拉力使人或物体朝向我们。", "教材 P.40 Forces"),
  "heavy": d("/ˈhevi/", "形容词", ["a heavy thing", "heavier than"], "It is easier to move a light thing than a heavy thing.", "移动轻的物体比移动重的物体更容易。", "教材 P.40 Movement"),
  "light": d("/laɪt/", "形容词", ["a light thing", "lighter than"], "It is easier to move a light thing than a heavy thing.", "移动轻的物体比移动重的物体更容易。", "教材 P.40 Movement"),
  "easy": d("/ˈiːzi/", "形容词", ["easy to move", "easier to move"], "It is easier to move a light thing than a heavy thing.", "移动轻的物体比移动重的物体更容易。", "教材 P.40 Movement"),
  "difficult": d("/ˈdɪfɪkəlt/", "形容词", ["difficult to move", "easy or difficult"], "It is easier to move a light thing than a heavy thing.", "移动轻的物体比移动重的物体更容易。", "教材 P.38 词汇栏；原句见 P.40"),
  "win": d("/wɪn/", "动词", ["win a game", "difficult to win"], "They pushed each other for a long time and got tired.", "他们互相推了很久，最后累了。", "教材 P.38 词汇栏；原句见 P.46"),
  "force": d("/fɔːs/", "名词", ["a small force", "a big force"], "A force can make something move.", "力可以使物体运动。", "教材 P.40 Forces"),
  "movement": d("/ˈmuːvmənt/", "名词", ["a small movement", "a big movement"], "A small force causes a small movement and a big force causes a big movement.", "小的力引起小的运动，大的力引起大的运动。", "教材 P.40 Movement"),
  "towards": d("/təˈwɔːdz/", "介词", ["move towards us", "towards a place"], "When we pull, it moves people or things towards us.", "当我们拉时，拉力使人或物体朝向我们。", "教材 P.40 Forces"),
  "cause": d("/kɔːz/", "动词", ["cause a movement", "causes a big movement"], "A small force causes a small movement and a big force causes a big movement.", "小的力引起小的运动，大的力引起大的运动。", "教材 P.40 Movement"),
  "speed": d("/spiːd/", "名词", ["change the speed", "high speed"], "Speed is how fast things move.", "速度就是物体运动得有多快。", "教材 P.41 Speed"),
  "tortoise": d("/ˈtɔːtəs/", "名词", ["like tortoises", "a tortoise moves slowly"], "Some things, like trains, move fast, and some things, like tortoises, move slowly.", "有些物体像火车一样移动得快，有些像陆龟一样移动得慢。", "教材 P.41 Speed"),
  "yourself": d("/jɔːˈself/", "反身代词", ["ask yourself", "protect yourself"], "Next time you see something moving, ask yourself, ‘What force is moving it, a push or a pull?’", "下次看到物体运动时，问问自己：使它运动的力是推力还是拉力？", "教材 P.41 Speed"),

  "invention": d("/ɪnˈvenʃən/", "名词", ["basic inventions", "the invention of"], "They are the most basic inventions.", "它们是最基本的发明。", "教材 P.52 Simple machines"),
  "slide": d("/slaɪd/", "名词", ["a slide", "a slide is a ramp"], "A slide is a ramp.", "滑梯是一种斜坡。", "教材 P.53 The ramp"),
  "seesaw": d("/ˈsiːsɔː/", "名词", ["ride on a seesaw", "a seesaw is a lever"], "A seesaw is also a lever.", "跷跷板也是一种杠杆。", "教材 P.52 The lever"),
  "watch": d("/wɒtʃ/", "名词；动词", ["an old watch", "inside a watch"], "Inside an old clock or watch, you can also see tiny wheels.", "在老式钟表或手表里面，你也能看到小轮子。", "教材 P.53 The wheel"),
  "lever": d("/ˈliːvə/", "名词", ["a bottle opener is a lever", "use a lever"], "A bottle opener is a lever.", "开瓶器是一种杠杆。", "教材 P.52 The lever"),
  "wheel": d("/wiːl/", "名词", ["use wheels", "tiny wheels"], "We use wheels every day on cars, trucks and bicycles.", "我们每天都在汽车、卡车和自行车上使用轮子。", "教材 P.53 The wheel"),
  "simple": d("/ˈsɪmpəl/", "形容词", ["simple machines", "a simple invention"], "What are simple machines?", "什么是简单机械？", "教材 P.52 Simple machines"),
  "machine": d("/məˈʃiːn/", "名词", ["simple machines", "use a machine"], "What are simple machines?", "什么是简单机械？", "教材 P.52 Simple machines"),
  "basic": d("/ˈbeɪsɪk/", "形容词", ["the most basic inventions", "basic tools"], "They are the most basic inventions.", "它们是最基本的发明。", "教材 P.52 Simple machines"),
  "everyday": d("/ˈevrideɪ/", "形容词", ["everyday inventions", "everyday life"], "Many everyday inventions are levers.", "许多日常发明都是杠杆。", "教材 P.52 The lever"),
  "playground": d("/ˈpleɪɡraʊnd/", "名词", ["in the playground", "a playground seesaw"], "When you ride on a seesaw in the playground, you are using a lever.", "当你在操场上玩跷跷板时，你就在使用杠杆。", "教材 P.52 The lever"),
  "point": d("/pɔɪnt/", "名词；动词", ["a point in the middle", "point to"], "In the picture, a boy sits down on one side, and his friend on the other side goes up.", "图中，一个男孩坐在一边，另一边的朋友就升了上去。", "教材 P.52 图注含 a point in the middle"),
  "truck": d("/trʌk/", "名词", ["cars, trucks and bicycles", "a truck wheel"], "We use wheels every day on cars, trucks and bicycles.", "我们每天都在汽车、卡车和自行车上使用轮子。", "教材 P.53 The wheel"),
  "inside": d("/ˌɪnˈsaɪd/", "介词；副词", ["inside a watch", "inside a building"], "Inside an old clock or watch, you can also see tiny wheels.", "在老式钟表或手表里面，你也能看到小轮子。", "教材 P.53 The wheel"),
  "tiny": d("/ˈtaɪni/", "形容词", ["tiny wheels", "a tiny machine"], "Inside an old clock or watch, you can also see tiny wheels.", "在老式钟表或手表里面，你也能看到小轮子。", "教材 P.53 The wheel"),
  "ramp": d("/ræmp/", "名词", ["use a ramp", "a slide is a ramp"], "A ramp has one high end and one low end.", "斜坡一端高，一端低。", "教材 P.53 The ramp"),
  "wheelchair": d("/ˈwiːltʃeə/", "名词", ["people in wheelchairs", "use a wheelchair"], "People in wheelchairs use ramps to go into and out of buildings.", "使用轮椅的人借助斜坡进出建筑。", "教材 P.53 The ramp"),
  "hill": d("/hɪl/", "名词", ["hills and mountains", "go up a hill"], "Hills and mountains are ramps in nature.", "小山和山脉是自然界中的斜坡。", "教材 P.53 The ramp"),
  "nature": d("/ˈneɪtʃə/", "名词", ["in nature", "ramps in nature"], "Hills and mountains are ramps in nature.", "小山和山脉是自然界中的斜坡。", "教材 P.53 The ramp"),
  "board": d("/bɔːd/", "名词", ["carry the boards", "wooden boards"], "They’ll use the cart to carry the boards.", "他们会用手推车运木板。", "教材 P.56 A"),
  "push down": d("/pʊʃ daʊn/", "动词短语", ["push down", "push down one side"], "In the picture, a boy sits down on one side, and his friend on the other side goes up.", "图中，一个男孩坐在一边，另一边的朋友就升了上去。", "教材 P.52 The lever 图注"),

  "shopping centre": d("/ˈʃɒpɪŋ ˌsentə/", "名词短语", ["go to a shopping centre", "in the shopping centre"], "There are many interesting places in a city.", "城市里有许多有趣的地方。", "教材 P.62 词汇栏；原句见 P.72"),
  "art gallery": d("/ɑːt ˈɡæləri/", "名词短语", ["go to an art gallery", "visit an art gallery"], "It is a quiet place for art lovers.", "对艺术爱好者来说，这是一个安静的地方。", "教材 P.62 B（art gallery 见同题词库）"),
  "amusement park": d("/əˈmjuːzmənt pɑːk/", "名词短语", ["go to amusement parks", "an amusement park"], "What can we do in a city?", "我们在城市里可以做什么？", "教材 P.69 B（搭配见同页活动清单）"),
  "historic building": d("/hɪˈstɒrɪk ˈbɪldɪŋ/", "名词短语", ["historic buildings", "see historic buildings"], "You can enjoy seeing Beijing’s historic buildings.", "你可以欣赏北京的历史建筑。", "教材 P.64 A historic city"),
  "modern building": d("/ˈmɒdən ˈbɪldɪŋ/", "名词短语", ["modern buildings", "amazing buildings"], "Today, it is full of modern buildings and green spaces.", "如今，这里到处是现代建筑和绿色空间。", "教材 P.71 From town to megacity"),
  "snapshot": d("/ˈsnæpʃɒt/", "名词", ["a city snapshot", "a big-city snapshot"], "Beijing: a big-city snapshot", "北京：大城市速览。", "教材 P.64 标题"),
  "nobody": d("/ˈnəʊbədi/", "代词", ["nobody can", "nobody gets bored"], "Nobody can be bored in Beijing!", "在北京，谁都不会觉得无聊！", "教材 P.64"),
  "bored": d("/bɔːd/", "形容词", ["be bored", "get bored"], "Nobody can be bored in Beijing!", "在北京，谁都不会觉得无聊！", "教材 P.64"),
  "emperor": d("/ˈempərə/", "名词", ["many emperors", "Chinese emperors"], "Many emperors once lived there.", "许多皇帝曾经住在那里。", "教材 P.64 A historic city"),
  "once": d("/wʌns/", "副词", ["once lived", "once a day"], "Many emperors once lived there.", "许多皇帝曾经住在那里。", "教材 P.64 A historic city"),
  "opera": d("/ˈɒpərə/", "名词", ["watch operas", "plays and operas"], "There, you can watch plays and operas.", "在那里，你可以看戏剧和歌剧。", "教材 P.65 Modern Beijing"),
  "sell": d("/sel/", "动词", ["people selling tasty food", "sell food"], "There are people selling tasty food and lots of snacks too.", "有人在卖美味的食物，还有许多小吃。", "教材 P.67 The big city"),
  "a mix of…": d("/ə mɪks əv/", "名词短语", ["a mix of old and new", "a mix of cultures"], "Beijing is a mix of old and new.", "北京是古老与现代的融合。", "教材 P.64"),
  "thousands of": d("/ˈθaʊzəndz əv/", "数量短语", ["thousands of years", "thousands of people"], "People built it thousands of years ago.", "人们在几千年前建造了它。", "教材 P.64 A historic city"),
  "take a trip": d("/teɪk ə trɪp/", "动词短语", ["take a trip", "take a trip to the Great Wall"], "Take a trip to see the Great Wall.", "去旅行，看看长城。", "教材 P.65 Top 3 things to do"),
  "a drop of": d("/ə drɒp əv/", "名词短语", ["a drop of water", "look like a drop of water"], "The National Centre for the Performing Arts looks like a drop of water.", "国家大剧院看起来像一滴水。", "教材 P.65 Modern Beijing"),
};
