import { createHash } from "node:crypto";
import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

import { wordDetails } from "../app/vocab-details.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const audioDir = path.join(root, "public", "audio", "tts");
const manifestFile = path.join(root, "app", "audio-manifest.ts");
const runtimePython = path.join(root, ".tts-runtime", "bin", "python");
const modelFile = path.join(root, ".tts-models", "kokoro-v1.0.onnx");
const voicesFile = path.join(root, ".tts-models", "voices-v1.0.bin");
const jobsFile = path.join(root, "work", "kokoro-jobs.json");
const batchScript = path.join(root, "scripts", "kokoro-batch.py");
const voice = process.env.KOKORO_VOICE || "bf_emma";
const speed = Number(process.env.KOKORO_SPEED || "0.90");

function cleanForSpeech(text) {
  return text
    .replaceAll("…", "")
    .replaceAll("one’s", "one's")
    .replaceAll("I’m", "I'm")
    .replace(/\bPS\b/g, "P. S.")
    .replace(/\bX-ray\b/gi, "X ray")
    .trim();
}

function collectTexts() {
  const details = Object.entries(wordDetails);
  const unitSizes = [13, 13, 16, 14, 21, 16];
  const texts = [];
  let offset = 0;

  for (const [word, detail] of details) {
    texts.push(word, ...detail.collocations, detail.bookSentence);
  }

  for (const size of unitSizes) {
    texts.push(details.slice(offset, offset + size).map(([word]) => word).join(". "));
    offset += size;
  }

  return [...new Set(texts.map((text) => text.trim()).filter(Boolean))];
}

function fileNameFor(text) {
  return `${createHash("sha256").update(text).digest("hex").slice(0, 20)}.m4a`;
}

async function fileExists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function requireFile(file, help) {
  if (!(await fileExists(file))) throw new Error(`${help}\nMissing: ${file}`);
}

async function writeManifest(texts) {
  const entries = [];
  for (const text of texts) {
    const fileName = fileNameFor(text);
    if (await fileExists(path.join(audioDir, fileName))) {
      entries.push([text, `/audio/tts/${fileName}`]);
    }
  }
  const manifest = Object.fromEntries(entries);
  const source = [
    "/** Generated by `npm run audio:generate`. Do not edit by hand. */",
    `export const audioManifest: Record<string, string> = ${JSON.stringify(manifest, null, 2)};`,
    "",
  ].join("\n");
  await writeFile(manifestFile, source, "utf8");
  return entries.length;
}

function runBatch() {
  return new Promise((resolve, reject) => {
    const child = spawn(runtimePython, [batchScript, jobsFile], {
      cwd: root,
      stdio: "inherit",
    });
    child.on("error", reject);
    child.on("exit", (code) => code === 0 ? resolve() : reject(new Error(`Kokoro batch exited with code ${code}`)));
  });
}

async function main() {
  const texts = collectTexts();
  if (process.argv.includes("--list")) {
    console.log(`TTS text count: ${texts.length}`);
    console.log(texts.join("\n"));
    return;
  }

  await requireFile(runtimePython, "Kokoro runtime is not installed. Run `npm run audio:setup` first.");
  await requireFile(modelFile, "Kokoro model is not installed. Run `npm run audio:setup` first.");
  await requireFile(voicesFile, "Kokoro voices are not installed. Run `npm run audio:setup` first.");
  await mkdir(audioDir, { recursive: true });
  await mkdir(path.dirname(jobsFile), { recursive: true });

  const jobs = [];
  for (const text of texts) {
    const output = path.join(audioDir, fileNameFor(text));
    if (!(await fileExists(output))) jobs.push({ text, spokenText: cleanForSpeech(text), output });
  }

  if (jobs.length) {
    await writeFile(jobsFile, JSON.stringify({ modelFile, voicesFile, voice, speed, jobs }, null, 2), "utf8");
    console.log(`Generating ${jobs.length} of ${texts.length} clips with Kokoro ${voice} at ${speed}× speed.`);
    await runBatch();
  }

  const manifestCount = await writeManifest(texts);
  if (manifestCount !== texts.length) throw new Error(`Only ${manifestCount}/${texts.length} audio files were generated.`);
  console.log(`Done. ${manifestCount} local British-English clips are ready.`);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
